name: My first workflow
on: 
  push:
    branches: 
      - main
      - "release/**"
jobs:
  MyfirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo "The repo ${{ github.repository}} contains the following files:"
          tree
